sudo: true

language: node_js

node_js:
  - "4"

cache:
  directories:
    - node_modules

before_install:

install: npm install

script: npm run coverage

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY_MRC5163
  app: nlp-app-sweng894
  on:
    all_branches: true
